DetailingBedrijf/Controllers/AfspraakController.cs
using DataLaag.DataToegang;
using DomeinLaag.DTOs;
using DomeinLaag.Exceptions;
using DomeinLaag.Interfaces;
using DomeinLaag.Logica;
using DomeinLaag.Mapping;
using DomeinLaag.Models;
using Microsoft.AspNetCore.Mvc;
using System.Reflection;
using Microsoft.Extensions.Configuration.Ini;

namespace DetailingBedrijf.Controllers
{
    public class AfspraakController : Controller
    {
        private AfspraakCollectie _collectie;
        private IConfiguration _configuration;
        private AfspraakMapping _mapping = new AfspraakMapping();

        public AfspraakController(IConfiguration configuration)
        {
            IAfspraak _afspraakData = new AfspraakDataToegang(configuration);
            IDetailer _detailerData = new DetailerDataToegang(configuration);
            AfspraakCollectie collectie = new AfspraakCollectie(_afspraakData, _detailerData);
            _collectie = collectie;
        }
        public IActionResult Index()
        {
            List<AfspraakModel> models = _collectie.HaalAllesOp();
            return View(models);
        }

        [HttpGet]
        [Route("Afspraak/Aanmaken")]
        public IActionResult Aanmaken()
        {
            return View(new AfspraakModel());
        }

        [HttpPost]
        public IActionResult Aanmaken(AfspraakModel model)
        {
            _collectie.Aanmaken(_mapping.MapModelNaarDTO(model));
            return RedirectToAction("Index", "Dashboard");
        }

        [HttpGet]
        public IActionResult Aanpassen()
        {
            return View(new AfspraakModel());
        }

        [HttpPost]
        [Route("Afspraak/Aanpassen/{id:int}")]
        public IActionResult Aanpassen(int id, AfspraakModel model)
        {
            _collectie.AanpassenOpID(id, model);
            return RedirectToAction("Index", "Dashboard");
        }

        [HttpGet]
        [Route("Afspraak/Details/{id:int}")]
        public IActionResult Details(int id)
        {
            AfspraakModel model = _collectie.HaalOpViaID(id);
            return View(model);
        }

        [Route("Afspraak/Verwijderen/{id}")]
        public IActionResult Verwijderen(int id)
        {
            _collectie.Verwijderen(id);
            return RedirectToAction("Index", "Dashboard");
        }

        [HttpGet]
        [Route("Afspraak/OphalenVoorDetailer/{detailerID:int}")]
        public IActionResult OphalenVoorDetailer(int detailerID)
        {
            List<AfspraakModel> models = _collectie.HaalOpVoorDetailer(detailerID);
            return View(models);
        }

        [HttpGet]
        [Route("Afspraak/AanmakenVoorDetailer/{detailerID:int}")]
        public IActionResult AanmakenVoorDetailer()
        {
            return View(new AfspraakModel());
        }

        [HttpPost]
        [Route("Afspraak/AanmakenVoorDetailer/{detailerID:int}")]
        public IActionResult AanmakenVoorDetailer(int detailerID, AfspraakModel model)
        {
            try
            {
                model.DetailerID = detailerID;
                _collectie.Aanmaken(_mapping.MapModelNaarDTO(model));
                return RedirectToAction("Index", "Dashboard");
            }
            catch (Exception divge)
            {
                Console.Write($"{divge.Message}\n {divge.InnerException}"); //Eerst specifieke catch daarna generiek.
                return RedirectToAction("Index", "Dashboard"); //return Error view model met message. 
                //DataAnnotations
            }
        }
    }
}

DetailingBedrijf/Controllers/DetailerController.cs
using DataLaag.DataToegang;
using DomeinLaag.DTOs;
using DomeinLaag.Interfaces;
using DomeinLaag.Logica;
using DomeinLaag.Mapping;
using DomeinLaag.Models;
using Microsoft.AspNetCore.Mvc;
using System.Configuration;

namespace DetailingBedrijf.Controllers
{ 
    public class DetailerController : Controller
    {
        private DetailerCollectie _collectie;
        private DetailerMapping _mapping = new DetailerMapping();

        public DetailerController(IConfiguration configuration)
        {
            IDetailer _data = new DetailerDataToegang(configuration);
            DetailerCollectie collectie = new DetailerCollectie(_data);
            _collectie = collectie;
        }
        public IActionResult Index()
        {
            List<DetailerModel> models = _collectie.HaalAllesOp();
            return View(models);
        }

        [HttpGet]
        [Route("Detailer/Aanmaken")]
        public IActionResult Aanmaken()
        {
            return View(new DetailerModel());
        }

        [HttpPost]
        public IActionResult Aanmaken(DetailerModel model)
        {
            _collectie.Aanmaken(_mapping.MapModelNaarDTO(model));
            return RedirectToAction("Index", "Dashboard");
        }

        [HttpGet]
        [Route("Detailer/Details/{id}")]
        public IActionResult Details(int id)
        {
            DetailerModel model = _collectie.HaalOpViaID(id);
            return View(model);
        }

        [Route("Detailer/Verwijderen/{id}")]
        public IActionResult Verwijderen(int id)
        {
            _collectie.Verwijderen(id);
            return RedirectToAction("Index", "Dashboard");
        }

        [HttpGet]
        [Route("Detailer/AfsprakenOphalen/{detailerID:int}")]
        public IActionResult OphalenVoorDetailer(int detailerID)
        {
            DetailerModel model = _collectie.AfsprakenOphalenOpID(detailerID);
            return View(model.AfsprakenDetailer);
        }
    }
}

DetailingBedrijf/Views/Detailer/Aanmaken.cshtml
@model DomeinLaag.Models.DetailerModel

@{
    ViewData["Title"] = "Aanmaken";
}

<h1>Aanmaken</h1>

<h4>DetailerModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Aanmaken">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Naam" class="control-label"></label>
                <input asp-for="Naam" class="form-control" />
                <span asp-validation-for="Naam" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DetailingBedrijf/Views/Detailer/Details.cshtml
@model DomeinLaag.Models.DetailerModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>DetailerModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DetailerID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DetailerID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Naam)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Naam)
        </dd>
    </dl>
</div>
<div>
    @*@Html.ActionLink("Edit", "Edit", new { id = Model.DetailerID }) |*@
    <a asp-action="Index">Back to List</a>
</div>

DetailingBedrijf/Views/Detailer/Index.cshtml
@model IEnumerable<DomeinLaag.Models.DetailerModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Aanmaken">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DetailerID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Naam)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DetailerID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Naam)
            </td>
            <td>
                @Html.ActionLink("Details", "Details", new { id = item.DetailerID }) |
                @Html.ActionLink("Verwijderen", "Verwijderen", new { id = item.DetailerID })
            </td>
        </tr>
}
    </tbody>
</table>

DetailingBedrijf/Views/Detailer/OphalenVoorDetailer.cshtml
@using Microsoft.AspNetCore.Razor.Language.Extensions
@model IEnumerable<DomeinLaag.Models.AfspraakModel>

@{
    ViewData["Title"] = "OphalenVoorDetailer";
}

<h1>OphalenVoorDetailer</h1>

<p>
    <a asp-action="Aanmaken">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DetailerID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AutoID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AfspraakID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DatumEnTijd)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DetailerID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AutoID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AfspraakID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DatumEnTijd)
            </td>
            <td>
                @Html.ActionLink("Details", "Details", "Afspraak",new { id = item.AfspraakID }) |
                @Html.ActionLink("Delete", "Verwijderen", "Afspraak", new { id = item.AfspraakID })
            </td>
        </tr>
}
    </tbody>
</table>